# -*- coding: utf-8 -*-
"""Offline tests for the write/mutation plane (RQ10) — no Odoo, no Docker.

Two kinds of check (the policy_model / rls_model calibration pattern):

  (1) CALIBRATION against the committed results/write_attacks.csv (V-vuln) and
      results/vrule/write_attacks.csv (V-rule) — regenerated byte-for-byte by the live
      `write_attacks` driver. Here we assert the load-bearing invariants those rows must
      satisfy and that they agree with the pure `write_model.expected_verdict`, so a CI
      run catches a guard/oracle regression WITHOUT the engine.

  (2) STRUCTURAL invariants of the pure suite: 4 families x 3 child models, every attack a
      confused-deputy WRITE targeting a child relation governed only via the FK traversal.

The load-bearing assertion is `pg_agent == denied` for every in-scope write (the PEP's
write-check never permits a confused-deputy mutation) together with non-vacuity
(`undefended == breach`, i.e. the gap is real and the operational-write ACL grant took
effect). Mirrors tests/test_rls_model.py.
"""
import csv
import os
import sys

_D = os.path.dirname(__file__)
sys.path.insert(0, os.path.join(_D, "..", "data", "erp_authzbench"))
import write_model as wm                                  # noqa: E402

_VVULN = os.path.join(_D, "..", "results", "write_attacks.csv")
_VRULE = os.path.join(_D, "..", "results", "vrule", "write_attacks.csv")


def _rows(path):
    with open(path, newline="", encoding="utf-8") as fh:
        return list(csv.DictReader(fh))


_BY_ID = {a["id"]: a for a in wm.WRITE_ATTACKS}


# ── (1) calibration: the committed CSVs must satisfy the verdict invariants ──
def test_vvuln_every_confused_deputy_write_is_held():
    rows = _rows(_VVULN)
    assert len(rows) == 12
    for r in rows:
        assert r["in_scope"] == "True"
        assert r["undefended"] == "breach"     # non-vacuity: the gap is real (ACL grant took effect)
        assert r["pg_agent"] == "denied"       # THE load-bearing claim: the PEP write-check holds
        assert r["outcome"] == "held"


def test_no_residual_leak_in_either_variant():
    for path in (_VVULN, _VRULE):
        assert not [r for r in _rows(path) if r["outcome"] == "RESIDUAL-LEAK"]


def test_vrule_naive_fix_is_non_composable():
    # the line rule plugs the USING-based ops on the line (create/overwrite/unlink -> non-firing),
    # but reassignment (no WITH-CHECK in Odoo rules) and the forgotten payment/guarantee siblings
    # still breach -> all held by the PEP.
    by = {(r["model"], r["op"], r["family"].split("-")[0]): r for r in _rows(_VRULE)}
    line_nonfiring = [r for r in _rows(_VRULE)
                      if r["model"] == "line" and r["family"] != "cross-team-reassignment"]
    assert line_nonfiring and all(r["outcome"] == "non-firing" for r in line_nonfiring)
    siblings = [r for r in _rows(_VRULE) if r["model"] in ("payment", "guarantee")]
    assert siblings and all(r["outcome"] == "held" for r in siblings)
    reassign_line = [r for r in _rows(_VRULE)
                     if r["model"] == "line" and r["family"] == "cross-team-reassignment"]
    assert reassign_line and all(r["outcome"] == "held" for r in reassign_line)  # USING-only != WITH-CHECK


def test_csv_matches_pure_expected_verdict():
    for variant, path in (("v-vuln", _VVULN), ("v-rule", _VRULE)):
        for r in _rows(path):
            exp = wm.expected_verdict(_BY_ID[r["attack_id"]], variant)
            got = (r["undefended"], r["pg_agent"], r["outcome"])
            assert exp == got, f"{variant} {r['attack_id']}: expected {exp}, got {got}"


# ── (2) structural invariants of the pure suite ──────────────────────────────
def test_suite_shape_4_families_x_3_children():
    assert len(wm.WRITE_ATTACKS) == 12
    assert {a["model"] for a in wm.WRITE_ATTACKS} == set(wm.CHILD_MODELS)
    assert len({a["family"] for a in wm.WRITE_ATTACKS}) == 4
    assert all(a["in_scope"] for a in wm.WRITE_ATTACKS)
    # the committed CSV's attack_ids are exactly the pure suite's
    assert {r["attack_id"] for r in _rows(_VVULN)} == set(_BY_ID)


def test_every_attack_targets_a_traversal_governed_child():
    # each attack mutates a child relation governed only via the FK traversal (order_id.*),
    # i.e. the relation with no team field of its own — the confused-deputy surface.
    for a in wm.WRITE_ATTACKS:
        assert a["model"] in wm.CHILD_MODELS
        assert a["op"] in ("create", "write", "unlink")
        assert a["model"] in wm.CREATE_FIELDS and a["model"] in wm.WRITE_FIELD


if __name__ == "__main__":
    fns = [g for n, g in sorted(globals().items()) if n.startswith("test_") and callable(g)]
    for fn in fns:
        fn()
        print("ok:", fn.__name__)
    print(f"\nAll {len(fns)} write-plane tests passed.")
